"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";

type View = "home" | "about" | "stations" | "news" | "records";
type ArchiveRecord = { id: string; title: string; date: string; level: number; kind: string; body: ReactNode };

const STORAGE_KEY = "shinonome-archive-progress-v1";
const REQUIRED_RECORDS = ["R-007", "W-817", "L-203", "OBS-817", "M-613", "AUD-04", "P-11", "AST-01", "AST-02", "M07-1", "STAFF-7", "PER-02", "FINAL-0"];
const normalize = (value: string) => value.normalize("NFKC").toLowerCase().replace(/[\s\u3000・ー—―_/:：.\-\\]/g, "");

const records: Record<string, ArchiveRecord> = {
  "R-007": { id: "R-007", title: "観測所台帳・欠番照会", date: "2001.04.01 移管", level: 1, kind: "施設台帳", body: <><p>台帳番号07は、平成10年9月30日付で廃止された<strong>「ミナセ第七観測所」</strong>に割り当てられていました。現在、施設概要は非公開です。</p><dl className="record-facts"><div><dt>所在地</dt><dd>東雲県水無瀬郡 柊沢北部</dd></div><div><dt>観測種別</dt><dd>局地気象・高層風・試験観測</dd></div><div><dt>廃止理由</dt><dd>落雷による設備損壊</dd></div></dl><div className="redacted-note">付記：8月17日の「<span>青い雨</span>」に関する照会は、資料課へ転送すること。</div></> },
  "W-817": { id: "W-817", title: "平成10年8月17日 異常降水照会", date: "1998.08.24", level: 2, kind: "照会記録", body: <><p>水無瀬郡柊沢地区より、降水の色に関する問い合わせが9件寄せられた。採取試料から着色物質は検出されず、公式回答は「街灯と低層雲による視覚現象」とした。</p><blockquote>雨は青かったのではありません。雨粒の中で、まだ朝になっていない空が光っていました。——風見郵便局 配達員の聞き取り</blockquote><p className="margin-note">関連事案コード：A-17 / 原資料2点</p></> },
  "L-203": { id: "L-203", title: "住民投書「夜明け前の放送」", date: "1998.08.19", level: 2, kind: "住民資料", body: <><p>資料室 御中</p><p>十七日の夜、停電中なのに防災無線から女の人の声がしました。「川から離れて」と三回。その直後、柊沢の水位が上がりました。あの放送がなければ、裏手の家は逃げ遅れていたと思います。</p><p>翌朝、役場へ聞くと放送記録はないと言われました。観測所の人ではないでしょうか。封筒の消印は<strong>風見郵便局</strong>、差出人名は雨で読めません。</p></> },
  "OBS-817": { id: "OBS-817", title: "A-17 自記気圧・降水観測表", date: "1998.08.17", level: 3, kind: "観測原簿", body: <><div className="weather-table" role="table" aria-label="8月17日の観測記録"><div role="row"><span>時刻</span><span>気圧</span><span>降水</span><span>備考</span></div><div role="row"><span>02:11</span><span>987.2</span><span>18.0</span><span>正常</span></div><div role="row"><span>02:12</span><span>986.9</span><span>21.5</span><span>針振れ</span></div><div className="missing-row" role="row"><span>02:13</span><span>欠測</span><span>欠測</span><span>記録紙切断</span></div><div role="row"><span>02:17</span><span>986.8</span><span>0.0</span><span>通信終了</span></div><div role="row"><span>02:18</span><span>990.1</span><span>0.0</span><span>無人</span></div></div><p>紙面裏に「欠測ではない。針は音を記録していた」と鉛筆書きあり。02:13開始の保守記録を参照。</p></> },
  "M-613": { id: "M-613", title: "緊急保守記録 02:13", date: "1998.08.17", level: 4, kind: "保守記録", body: <><dl className="record-facts"><div><dt>担当</dt><dd>冬木 梢・常盤 要</dd></div><div><dt>対象</dt><dd>自記気圧計 B-4</dd></div><div><dt>症状</dt><dd>入力なしの状態で記録針が周期振動</dd></div></dl><p>振動は雑音ではなく、長短二種の一定間隔を持つ。常盤は「針音」と呼び、記録紙04へ転写した。冬木の判断によりA棟送信機を観測計へ直結。</p><p className="stamp stamp-alert">添付：針音転写 04</p></> },
  "AUD-04": { id: "AUD-04", title: "針音転写 04 / 読み取りメモ", date: "1998.08.17 02:14", level: 4, kind: "転写資料", body: <><div className="signal" aria-label="短い線と長い線が並ぶ記録"><span className="short"/><span className="long"/><span className="short"/><i/><span className="long"/><span className="long"/><span className="short"/><i/><span className="short"/><span className="short"/><span className="long"/></div><div className="hand-note"><p><b>し</b>ずかな夜ほど、針は大きく鳴った。</p><p><b>お</b>なじ間隔を三度くり返している。</p><p><b>り</b>ゆうを知りたければ、彼女が最初に残したものを読め。</p></div><p className="margin-note">筆跡照合：常盤 要</p></> },
  "P-11": { id: "P-11", title: "冬木梢の私物しおり", date: "1998.08.18 回収", level: 5, kind: "回収物", body: <><p>観測手帳に挟まれていた厚紙。表面には施設内の地点記号、裏面には巡回順が記されている。</p><div className="route-card"><div><b>A</b><span>北棟観測室</span></div><div><b>S</b><span>南塔</span></div><div><b>T</b><span>送信室</span></div><div><b>E</b><span>東斜面</span></div><div><b>R</b><span>記録庫</span></div></div><p className="handwritten">風は 北棟観測室 → 南塔 → 送信室 → 東斜面 → 記録庫 の順。地点記号で読んで。</p></> },
  "AST-01": { id: "AST-01", title: "ASTER計画 実施要綱（抄）", date: "1997.11.03", level: 6, kind: "試験計画", body: <><p>大気共鳴記録実験 ASTERは、微気圧変動に含まれる生体由来信号を記録・再生する試みである。被験者の短期記憶を気圧計の機械振動として最大六分間保持する。</p><div className="warning-box">本実験を気象制御へ転用してはならない。共鳴域で強い降水が発生した場合、記録信号が周辺の放送設備へ混入する可能性がある。</div><p>第七観測所担当観測員：<strong>冬木 梢</strong> / 実験記録 M-07</p></> },
  "AST-02": { id: "AST-02", title: "ASTER計画 中止決裁", date: "1998.08.20", level: 7, kind: "決裁文書", body: <><p>A-17事案により、試験装置と局地降水の因果関係を否定できない。対外的には落雷事故として処理し、第七観測所を閉鎖する。住民避難に寄与した混信放送については存在を認めない。</p><p>観測員一名の安否は確認できず。残留信号を「個人の記録」と認めた場合、当室には保存義務が生じるため、M-07は機器雑音として廃棄対象とする。</p><p className="stamp stamp-alert">廃棄未了</p></> },
  "M07-1": { id: "M07-1", title: "M-07 残留信号・仮転記", date: "1998.08.17 02:13–02:17", level: 8, kind: "音声転記", body: <><div className="transcript"><p><time>02:13:08</time><span>……こちら第七。放送回線は切れている。</span></p><p><time>02:13:31</time><span>ASTERを気圧計へ接続。私の声が残るなら、柊沢へ流して。</span></p><p><time>02:14:02</time><span>川から離れて。東斜面へ。夜明けまで戻らないで。</span></p><p><time>02:16:44</time><span>梢です。これを記録として見つけた人へ。</span></p><p><time>02:16:58</time><span>終了時刻と、妹の名前を索引に。そうすれば原記録が開く。</span></p><p><time>02:17:00</time><span>澪に、空はちゃんと朝になると——</span></p></div><p>信号は02:17で停止。原記録は二要素照合で保護されている。</p></> },
  "STAFF-7": { id: "STAFF-7", title: "第七観測所 職員名簿", date: "1998.04.01", level: 6, kind: "人事記録", body: <><div className="staff-list"><div><b>冬木 梢</b><span>主任観測員 / ASTER担当</span></div><div><b>常盤 要</b><span>機器保守 / 通信</span></div><div><b>小坂 英二</b><span>局地観測 / 8月17日休務</span></div></div><p>緊急連絡先の欄に「妹・冬木 澪」とある。本人の希望により、事故後の連絡記録は別紙扱い。</p></> },
  "PER-02": { id: "PER-02", title: "冬木澪 宛未発送通知", date: "1998.08.21", level: 7, kind: "連絡記録", body: <><p>冬木 澪 様</p><p>ご家族である冬木梢職員につきまして、施設事故発生以降、所在確認を継続しております。私物の返還準備が整い次第ご連絡いたします。</p><p className="redacted-note">未発送理由：原記録に個人名が残存。存在を通知すればASTER計画の開示が必要となるため。</p></> },
  "MAIL-19": { id: "MAIL-19", title: "風見郵便局 臨時配達日誌", date: "1998.08.18", level: 3, kind: "寄贈資料", body: <><p>未明の避難誘導により、柊沢北部38世帯の無事を確認。局舎屋根の青い反射光については原因不明。02:14頃、防災無線から女性の声を聴取した者が複数いる。</p><p className="margin-note">寄贈者注：あれは警報ではなく、誰かの記憶だったのだと思う。</p></> },
  "YN-3": { id: "YN-3", title: "夕凪現象に関する技術注記", date: "1997.12.12", level: 5, kind: "技術資料", body: <><p>大気の動きが局所的に停止した際、気圧記録に観測者の呼吸・発声周期と一致する揺らぎが現れる。ASTER班はこれを「夕凪現象」と仮称した。</p><p>再生された情報は事実そのものではなく、記録者が最後に知覚した六分間である。</p></> },
  "LOST-6": { id: "LOST-6", title: "空白の六分間 / 復元仕様", date: "1998.08.22", level: 8, kind: "復元資料", body: <><p>M-07の記録長は3分52秒。ASTERの理論上限である六分間には達していない。これは記録者が途中で装置から離れたためであり、残りの時間は失われたのではなく、まだ記録されていない。</p><p className="handwritten">見つけた人が続きを決める。記録は、読まれたときに初めて天気になる。</p></> },
  "FINAL-0": { id: "FINAL-0", title: "M-07 原記録 / 復元承認", date: "照合完了", level: 9, kind: "最終記録", body: <><p>二要素照合を確認しました。冬木梢観測員の残留信号は機器雑音ではなく、柊沢地区の避難を促した記録として復元可能です。</p><blockquote>澪へ。約束した朝焼けは見られなかった。でも、空は誰かが見てくれる。私がここにいたことを、天気のせいにしないで。</blockquote><p>この記録を公開すると、第七観測所の欠番は正式に復元されます。個人記録として保全した場合、声は資料室内に残り、一般索引には掲載されません。</p></> },
};

const routes = [
  { terms: ["第七観測所", "第7観測所", "ミナセ第七観測所", "欠番"], ids: ["R-007"] },
  { terms: ["青い雨"], ids: ["W-817", "L-203"] },
  { terms: ["A17", "A-17", "1998年8月17日", "平成10年8月17日"], ids: ["OBS-817"] },
  { terms: ["02:13", "2時13分", "欠測"], ids: ["M-613"] },
  { terms: ["針音", "針音転写04"], ids: ["AUD-04"] },
  { terms: ["しおり", "冬木梢のしおり"], ids: ["P-11"] },
  { terms: ["ASTER", "アスター"], ids: ["AST-01", "AST-02"] },
  { terms: ["M-07", "M07"], ids: ["M07-1"] },
  { terms: ["冬木梢"], ids: ["STAFF-7"] },
  { terms: ["冬木澪", "澪"], ids: ["PER-02"] },
  { terms: ["02:17 澪", "澪 02:17", "0217澪", "澪0217"], ids: ["FINAL-0"] },
  { terms: ["風見郵便局"], ids: ["MAIL-19"] }, { terms: ["夕凪現象", "夕凪"], ids: ["YN-3"] }, { terms: ["空白の六分間", "六分間"], ids: ["LOST-6"] },
];
const hints = ["観測所一覧には、06と08の間に欠番があります。番号を言葉にして検索してください。", "欠番の記録に残された、色のついた雨の呼び名を検索してください。", "異常降水の資料には、短い事案コードが記されています。", "観測表で唯一『欠測』になっている時刻を調べてください。", "保守記録の添付資料名を、そのまま検索してください。", "転写資料の手書きメモは、各行の最初の文字に癖があります。", "しおりの巡回順を、左側の地点記号に置き換えてください。", "計画書に記された実験記録コードを検索してください。", "残留信号を残した観測員の名前を調べると、家族の情報に辿り着きます。", "最後の照合は、通信終了時刻と妹の名前を空白で区切って入力します。"];

function RecordCard({ record }: { record: ArchiveRecord }) {
  return <article className={`record-card level-${Math.min(record.level, 8)}`}><header className="record-header"><div><span className="record-kind">{record.kind}</span><h3>{record.title}</h3></div><div className="record-meta"><span>LEVEL {record.level}</span><code>{record.id}</code></div></header><div className="record-date">記録日：{record.date}</div><div className="record-body">{record.body}</div></article>;
}

export default function Home() {
  const [view, setView] = useState<View>("home"), [query, setQuery] = useState(""), [searched, setSearched] = useState(""), [resultIds, setResultIds] = useState<string[]>([]), [discovered, setDiscovered] = useState<string[]>([]), [message, setMessage] = useState("");
  const [showNotebook, setShowNotebook] = useState(false), [showGuide, setShowGuide] = useState(false), [showSafety, setShowSafety] = useState(false), [hintLevel, setHintLevel] = useState(0), [ending, setEnding] = useState<"public" | "private" | null>(null), [loaded, setLoaded] = useState(false);
  const searchInput = useRef<HTMLInputElement>(null);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "null"); if (Array.isArray(saved?.discovered)) setDiscovered(saved.discovered); if (saved?.ending === "public" || saved?.ending === "private") setEnding(saved.ending); } catch {} setLoaded(true); }, []);
  useEffect(() => { if (loaded) localStorage.setItem(STORAGE_KEY, JSON.stringify({ discovered, ending })); }, [discovered, ending, loaded]);
  const requiredFound = useMemo(() => REQUIRED_RECORDS.filter(id => discovered.includes(id)).length, [discovered]);
  const progress = Math.round(requiredFound / REQUIRED_RECORDS.length * 100);

  function runSearch(event: FormEvent) {
    event.preventDefault(); const trimmed = query.trim(); if (!trimmed) { setMessage("検索語を入力してください。"); return; }
    setSearched(trimmed); setView("records"); const n = normalize(trimmed); const route = routes.find(r => r.terms.some(t => normalize(t) === n));
    if (route) { setResultIds(route.ids); setDiscovered(cur => Array.from(new Set([...cur, ...route.ids]))); setMessage(`${route.ids.length}件の記録が見つかりました。`); setTimeout(() => document.getElementById("search-results")?.focus(), 0); return; }
    const partial = routes.some(r => r.terms.some(t => n.length >= 2 && (normalize(t).includes(n) || n.includes(normalize(t))))); setResultIds([]); setMessage(partial ? "関連する索引語です。資料に記された固有名詞・時刻を、表記どおりに入力してください。" : "公開索引に一致する記録はありません。別の語句、人物名、時刻、資料番号をお試しください。");
  }
  function navigate(next: View) { setView(next); setShowNotebook(false); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function reopenRecord(id: string) { setResultIds([id]); setSearched(records[id].title); setMessage("発見済み記録を開いています。"); setView("records"); setShowNotebook(false); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function resetProgress() { if (!confirm("この端末に保存された調査記録と結末を消去しますか？")) return; setDiscovered([]); setEnding(null); setResultIds([]); setSearched(""); setQuery(""); localStorage.removeItem(STORAGE_KEY); setShowNotebook(false); setView("home"); }

  return <main className={ending ? `site ending-${ending}` : "site"}>
    <div className="utility-bar"><div className="utility-inner"><span>東雲県 デジタル資料公開基盤</span><div><button onClick={() => setShowGuide(true)}>資料検索の使い方</button><button onClick={() => setShowSafety(true)}>このサイトについて</button></div></div></div>
    <header className="site-header"><button className="brand" onClick={() => navigate("home")} aria-label="資料室トップへ"><span className="brand-mark" aria-hidden="true"><i/><i/><i/></span><span><b>東雲地方気象資料室</b><small>SHINONOME REGIONAL METEOROLOGICAL ARCHIVE</small></span></button><div className="header-status"><span className="status-dot"/><span>公開資料システム</span><b>正常</b></div></header>
    <nav className="primary-nav" aria-label="主要メニュー"><div><button className={view === "home" ? "active" : ""} onClick={() => navigate("home")}>資料室トップ</button><button className={view === "about" ? "active" : ""} onClick={() => navigate("about")}>資料室について</button><button className={view === "stations" ? "active" : ""} onClick={() => navigate("stations")}>観測所一覧</button><button className={view === "news" ? "active" : ""} onClick={() => navigate("news")}>更新情報</button><button className="notebook-nav" onClick={() => setShowNotebook(true)}>調査記録 <span>{discovered.length}</span></button></div></nav>
    <section className="search-band" aria-label="資料検索"><div className="search-band-inner"><div><span className="eyebrow">ARCHIVE SEARCH</span><h1>観測資料を検索</h1><p>地名、観測所名、日付、資料番号などを入力してください。</p></div><form className="search-form" onSubmit={runSearch}><label htmlFor="archive-search">検索語</label><div><input ref={searchInput} id="archive-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="例：観測所名、記録日、資料番号" autoComplete="off"/><button type="submit">資料を検索</button></div><small>複数の語を組み合わせる場合は、空白で区切ってください。</small></form></div></section>
    <div className="page-shell"><aside className="sidebar"><section className="weather-now"><span className="eyebrow">ARCHIVE WEATHER</span><div className="weather-icon" aria-hidden="true"><i/><i/><i/></div><div className="temperature">17.8<sup>°C</sup></div><b>薄曇</b><dl><div><dt>気圧</dt><dd>1012.4 hPa</dd></div><div><dt>風向</dt><dd>東北東</dd></div><div><dt>更新</dt><dd>02:12</dd></div></dl><p className="sensor-note">一部観測点でデータ欠測中</p></section><section className="progress-card"><div className="progress-heading"><span>資料復元率</span><b>{progress}%</b></div><div className="progress-track"><i style={{ width: `${progress}%` }}/></div><p>{requiredFound} / {REQUIRED_RECORDS.length} 件の主要記録を確認</p><button onClick={() => setShowNotebook(true)}>発見した資料を見る</button></section><section className="side-help"><b>調査に行き詰まった場合</b><p>検索語は公開ページや発見済み資料の中にあります。</p><button onClick={() => setShowGuide(true)}>段階式ヒントを表示</button></section></aside>
      <div className="content-area">
        {view === "home" && <>{ending && <section className={`ending-banner ${ending}`}><span>{ending === "public" ? "RESTORED" : "PRESERVED"}</span><h2>{ending === "public" ? "第七観測所の記録は復元されました" : "M-07は個人記録として保全されています"}</h2><p>{ending === "public" ? "欠番は台帳へ戻り、冬木梢観測員の名前と避難放送が公開記録に加えられました。" : "一般索引は変わりません。ただし、資料室は彼女の声を機器雑音として廃棄しないことを決定しました。"}</p></section>}<section className="hero-notice"><div className="notice-date"><b>12</b><span>JUL<br/>2026</span></div><div><span className="eyebrow">DIGITAL ARCHIVE</span><h2>過去の気象を、地域の記憶へ。</h2><p>東雲地方気象資料室では、明治期から現在までの観測原簿、施設台帳、地域気象資料をデジタル化し、順次公開しています。</p></div></section><section className="section-block"><div className="section-title"><div><span className="eyebrow">INFORMATION</span><h2>更新情報</h2></div><button onClick={() => navigate("news")}>一覧を見る</button></div><div className="news-list"><article><time>2026.07.07</time><span>資料公開</span><p>平成10年度・水無瀬郡局地観測資料のデジタル化が完了しました。</p></article><article><time>2026.06.21</time><span>お知らせ</span><p>欠番資料の照会方法について、検索案内を更新しました。</p></article><article><time>2026.05.30</time><span>保守情報</span><p>旧式自記気圧計データの一部で時刻表示に欠測が確認されています。</p></article></div></section><section className="archive-intro"><div><span className="eyebrow">HOW TO SEARCH</span><h2>資料を探す</h2><p>上部の検索欄へ、資料に書かれた固有名詞や番号を入力してください。施設台帳では、廃止された観測所を含む記録も検索できます。</p><button onClick={() => navigate("stations")}>観測所一覧から探す</button></div><div className="archive-boxes" aria-hidden="true"><div><i>01</i><span>観測原簿</span></div><div><i>02</i><span>施設台帳</span></div><div className="archive-gap"><i>—</i><span>欠番資料</span></div><div><i>04</i><span>地域資料</span></div></div></section></>}
        {view === "about" && <section className="static-page"><span className="eyebrow">ABOUT US</span><h2>東雲地方気象資料室について</h2><p className="lead">当資料室は、東雲地方における気象観測の歴史を保存し、地域防災と調査研究に役立てるための公開アーカイブです。</p><div className="about-grid"><article><b>1891</b><span>東雲測候所 開設</span><p>県内初の定時気象観測を開始。</p></article><article><b>1954</b><span>地域観測網 整備</span><p>山間部を含む8観測所へ拡大。</p></article><article><b>2001</b><span>資料室へ移管</span><p>廃止施設の原簿と機器を収蔵。</p></article><article><b>2024</b><span>デジタル公開</span><p>約7万件の資料を順次索引化。</p></article></div><div className="policy-note"><h3>資料番号について</h3><p>廃棄、移管未了、事故資料などの理由で、公開台帳には欠番があります。欠番資料も正式名称が判明している場合は検索できます。</p></div></section>}
        {view === "stations" && <section className="static-page"><span className="eyebrow">OBSERVATORIES</span><h2>観測所一覧</h2><p className="lead">東雲地方気象資料室が記録を保管する旧地域観測所の一覧です。</p><div className="station-list">{[["01","東雲中央測候所","東雲市","現用"],["02","海凪沿岸観測所","海凪町","現用"],["03","鐘守山岳観測所","鐘守村","1999廃止"],["04","柊沢雨量観測所","水無瀬郡","2008移設"],["05","日暮高層風観測所","日暮町","1995廃止"],["06","水無瀬第一観測所","水無瀬郡","2001廃止"]].map(row => <div key={row[0]}><code>{row[0]}</code><b>{row[1]}</b><span>{row[2]}</span><em>{row[3]}</em></div>)}<div className="station-missing"><code>07</code><b>記録なし</b><span>—</span><em>欠番</em></div><div><code>08</code><b>白萩盆地観測所</b><span>白萩町</span><em>2001廃止</em></div></div><p className="index-clue">欠番の旧称に関する照会は、番号を漢数字で検索してください。</p></section>}
        {view === "news" && <section className="static-page"><span className="eyebrow">INFORMATION</span><h2>更新情報</h2><div className="news-page-list"><article><time>2026.07.07</time><h3>水無瀬郡局地観測資料を追加しました</h3><p>平成10年8月分を含む観測原簿1,204点を公開索引へ追加しました。一部の資料は保存状態により本文検索の対象外です。</p></article><article><time>2026.06.21</time><h3>欠番資料の照会方法について</h3><p>資料番号が欠番でも、施設の正式名称が分かる場合は検索可能です。一般名ではなく、台帳上の名称をご利用ください。</p></article><article><time>2026.05.30</time><h3>旧式自記気圧計データの欠測</h3><p>平成10年度の一部記録で、02時13分からの時刻表示に異常があります。原資料の確認作業を継続しています。</p></article><article><time>2026.04.12</time><h3>寄贈資料の受け入れ</h3><p>旧風見郵便局より、柊沢地区の災害時配達日誌をご寄贈いただきました。</p></article></div></section>}
        {view === "records" && <section className="results-page" id="search-results" tabIndex={-1}><div className="results-heading"><div><span className="eyebrow">SEARCH RESULT</span><h2>「{searched}」の検索結果</h2></div><span className="result-count">{resultIds.length} 件</span></div><div className={`search-message ${resultIds.length ? "success" : "empty"}`} role="status" aria-live="polite">{message}</div>{resultIds.length ? <div className="record-stack">{resultIds.map(id => <RecordCard key={id} record={records[id]}/>)}</div> : <div className="empty-state"><div className="empty-glyph">?</div><h3>該当する公開記録がありません</h3><p>資料内で強調されている固有名詞、時刻、資料番号を確認してください。</p><button onClick={() => searchInput.current?.focus()}>検索欄へ戻る</button></div>}{resultIds.includes("FINAL-0") && !ending && <section className="decision-panel"><span className="eyebrow">ARCHIVE DECISION</span><h2>記録の扱いを選択してください</h2><p>この選択は、この端末上の資料室に反映されます。どちらも冬木梢の記録を失わせる選択ではありません。</p><div><button onClick={() => { setEnding("public"); navigate("home"); }}><b>公開記録として復元</b><span>欠番を台帳へ戻し、誰でも検索できるようにする</span></button><button onClick={() => { setEnding("private"); navigate("home"); }}><b>個人記録として保全</b><span>一般索引には載せず、資料室内で永久保存する</span></button></div></section>}</section>}
      </div>
    </div>
    <footer className="site-footer"><div><button className="footer-brand" onClick={() => navigate("home")}>東雲地方気象資料室</button><p>本サイトは公開アーカイブの閲覧体験を目的としています。</p></div><div><button onClick={() => setShowGuide(true)}>検索の使い方</button><button onClick={() => setShowSafety(true)}>安全と作品情報</button><button onClick={resetProgress}>調査記録を消去</button></div><small>© 2026 Shinonome Regional Meteorological Archive</small></footer>
    {showNotebook && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setShowNotebook(false)}><section className="modal notebook" role="dialog" aria-modal="true" aria-labelledby="notebook-title"><button className="modal-close" onClick={() => setShowNotebook(false)} aria-label="閉じる">×</button><span className="eyebrow">INVESTIGATION LOG</span><h2 id="notebook-title">調査記録</h2><div className="notebook-progress"><div><span>主要記録</span><b>{requiredFound} / {REQUIRED_RECORDS.length}</b></div><div className="progress-track"><i style={{ width: `${progress}%` }}/></div></div>{discovered.length ? <div className="notebook-list">{discovered.map((id, index) => <button key={id} onClick={() => reopenRecord(id)}><span>{String(index + 1).padStart(2,"0")}</span><div><b>{records[id].title}</b><small>{records[id].kind} / {records[id].id}</small></div><i>開く</i></button>)}</div> : <div className="notebook-empty"><p>まだ記録を発見していません。</p><span>観測所一覧の欠番から調査を始めてください。</span></div>}</section></div>}
    {showGuide && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setShowGuide(false)}><section className="modal guide" role="dialog" aria-modal="true" aria-labelledby="guide-title"><button className="modal-close" onClick={() => setShowGuide(false)} aria-label="閉じる">×</button><span className="eyebrow">SEARCH GUIDE</span><h2 id="guide-title">資料検索の使い方</h2><ol className="guide-steps"><li><b>違和感を見つける</b><span>公開ページの欠番、時刻、固有名詞を確認します。</span></li><li><b>索引へ入力する</b><span>資料に書かれた語を、できるだけそのまま検索します。</span></li><li><b>資料を照合する</b><span>発見した記録同士の日付・人物・番号をつなぎます。</span></li></ol><div className="hint-box"><div><b>段階式ヒント {hintLevel + 1} / {hints.length}</b><button onClick={() => setHintLevel(0)}>最初に戻す</button></div><p>{hints[hintLevel]}</p><button disabled={hintLevel >= hints.length - 1} onClick={() => setHintLevel(l => Math.min(l + 1, hints.length - 1))}>次のヒントを見る</button></div></section></div>}
    {showSafety && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setShowSafety(false)}><section className="modal safety" role="dialog" aria-modal="true" aria-labelledby="safety-title"><button className="modal-close" onClick={() => setShowSafety(false)} aria-label="閉じる">×</button><span className="eyebrow">ABOUT THIS EXPERIENCE</span><h2 id="safety-title">安全と作品情報</h2><p>「東雲地方気象資料室」はフィクションのWeb探索型ARGです。登場する自治体、施設、人物、災害、計画はすべて架空です。</p><ul><li>サイト内だけで最後まで遊べます。外部の人物・施設への連絡や訪問は必要ありません。</li><li>個人情報の入力、ファイルのダウンロード、ソースコードの解析は必要ありません。</li><li>進捗はこの端末のブラウザ内だけに保存され、外部へ送信されません。</li><li>突然の大音量、点滅、時間制限、失敗による進行不能はありません。</li></ul><button className="safety-continue" onClick={() => setShowSafety(false)}>資料室へ戻る</button></section></div>}
  </main>;
}
